### PR TITLE
Update for Minecraft 1.11.2 and additions for devs

### PR DESCRIPTION
**Pull request by KiriCattus**
Updated the Minecraft version the mod runs with and added a bunch of developer tools including the cursegradle task to upload to curseforge without having to fiddle about yourself.

(API key needed and project ID. Both should be put in the private.properties and build.properties file when running ``./gradlew curseforge``. Note: ``./`` is for powershell or unix based systems but you should know that right :p)

### CODE REVIEW

**Comment by GodsVictory** [comment]
nice work!

**Comment by KiriCattus** [comment]
Thanks! lol I hope the scripts will be useful for other projects of yours too :)

**Comment by GodsVictory** [comment]
Definitely!

**Comment by GodsVictory** [comment]
I added you as a contributor to the project page

**Comment by KiriCattus** [comment]
Thanks for that lol would you like me to upload a release later or have you tried out the curseforge script? Have a go it's quite intresting haha

**Comment by KiriCattus** [comment]
Never mind after checking the page your already a step ahead :)

**Pull request merged**
